FROM centos:latest

# Configure the container for SSH
RUN yum -y update --setopt=tsflags=nodocs \
    && yum -y install bind bind-utils \
    && yum -y install openssh-server openssh

RUN  /etc/init.d/sshd start

RUN sshd-keygen
#RUN mkdir -p /var/run/sshd
RUN echo 'root:password' | chpasswd
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

#ENV NOTVISIBLE "in users profile"
#RUN echo "export VISIBLE=now" >> /etc/profile

# Installing bind and installing the correct files
RUN echo " " > /etc/named.conf

ADD named.conf /etc/
RUN mkdir -p /var/named/slaves
RUN touch /var/named/slaves/locust.ulcert.uw.edu.txt
#RUN service named start

EXPOSE 22 53
EXPOSE 53/udp

CMD ["/usr/sbin/sshd", "-D"]

