---
- name: Configure server with docker
  hosts: ubuntu 
  become: yes 
  tasks:

    - name: "Install is starting"
      apt: update_cache=yes state=latest name={{ item }}
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl

    - name: "Adding keys to apt"
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        validate_certs: no
  
    - name: "Adding docker repository to ubuntu"
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu xenial stable 
        state: present
        update_cache: yes
        
    - name: "Install Docker"
      apt:
        name: docker-ce
        state: latest
        update_cache: yes
