---
- name: Configure server with docker
  hosts: control
  become: true 
  tasks:

    - name: "Install is starting."
      apt: name={{ item }}
      state: latest
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
    
    - name: "Update and Install Docker"
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: curl down keys
      command: >
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

    - name: "Adding docker repository to ubuntu"
      command: >
          add-apt-repository \
          "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) stable"

    - name: "Update and Install Docker"
      apt:
        name: docker-ce
        state: latest
        update_cache: true
