---
- name: iptables baseline
  hosts: ubuntu
  become: true
  tasks:

      - name: "DNAT from specific hosts"
        iptables:
          table: nat
          in_interface: ens33
          source: 140.142.159.0/24
          protocol: tcp
          destination_port: 514
          chain: PREROUTING
          jump: DNAT
          to_destination: 172.17.0.3
          action: insert
