---
- name: "rsyslog container"
  hosts: ubuntu
  become: true
  tasks:
    - name: "Creating rsyslog"
      docker_container:
        name: rsyslog
        hostname: rsyslogd
        image: bgalloway/rsyslog
        ports:
          - 514:514
          - 514:514/udp
        volumes:
          - /data/rsyslog:/data/rsyslog
        detach: true


